Lead Merger/force-app/main/default/objects/CustomLog__c/CustomLog__c.object-meta.xml
<CustomObject>
    <label>Custom Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lead Merger/force-app/main/default/objects/CustomLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Lead Merger/force-app/main/default/classes/LeadDuplicateMergerTest.cls
@IsTest
private class LeadDuplicateMergerTest {

    @TestSetup
    public static void setup() {

        insert new List<Lead>{
            new Lead(LastName='Test Name', Company='Test Company', Email='test@test.com', Phone='123', LeadSource='Phone'),
            new Lead(LastName='Test Name', Company='Test Company', Email='test@test.com', Phone='123', LeadSource='Phone'),
            new Lead(LastName='Test Name', Company='Test Company', Email='test@test.com', Phone='999', LeadSource='Phone')
        };
    }

    @isTest
    public static void processBatchTest() {

        List<Lead> listLeads = [SELECT Id FROM Lead WHERE Email='test@test.com'];

        Test.startTest();
            LeadDuplicateMerger.processBatch(listLeads);
        Test.stopTest();

        listLeads = [SELECT Id FROM Lead WHERE Email='test@test.com'];
        Assert.areEqual(1, listLeads.size());

        List<CustomLog__c> logs = [SELECT Type__c, Message__c FROM CustomLog__c WHERE RelatedRecordId__c = :listLeads[0].Id];
        Assert.isTrue(logs.size() > 0);
    }
}