Lead Merger/force-app/main/default/objects/CustomLog__c/CustomLog__c.object-meta.xml
<CustomObject>
    <label>Custom Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lead Merger/force-app/main/default/objects/CustomLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Lead Merger/force-app/main/default/classes/CustomLoggerTest.cls
@IsTest
private class CustomLoggerTest {

    @isTest
    public static void logTest() {

        CustomLogger logger = CustomLogger.getInstance();
        logger.log('Test message 1', 'INFO', null);
        logger.log('Test message 2', 'ERROR', null);

        Test.startTest();
            logger.flush();
        Test.stopTest();

        List<CustomLog__c> logs = [SELECT Message__c,Type__c,RelatedRecordId__c FROM CustomLog__c WHERE Message__c LIKE 'Test message%'];
        Assert.areEqual(2, logs.size());
        
        for (CustomLog__c rec : logs) {
            if (rec.Message__c == 'Test message 1') {
                Assert.areEqual('INFO', rec.Type__c);
                Assert.areEqual(null, rec.RelatedRecordId__c);
            } else {
                Assert.areEqual('ERROR', rec.Type__c);
                Assert.areEqual(null, rec.RelatedRecordId__c);
            }
        }
    }

    @isTest
    public static void flushTest() {

        CustomLogger logger = CustomLogger.getInstance();

        Test.startTest();
            logger.flush();
        Test.stopTest();
        
        Integer countAfter = [SELECT COUNT() FROM CustomLog__c];
        Assert.isTrue(countAfter == 0);
    }
}