Lead Merger/force-app/main/default/objects/CustomLog__c/CustomLog__c.object-meta.xml
<CustomObject>
    <label>Custom Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lead Merger/force-app/main/default/objects/CustomLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Lead Merger/force-app/main/default/classes/LeadTriggerTest.cls
@IsTest
private class LeadTriggerTest {
    private static final Integer numberOfLogs = 1;

    @isTest
    public static void triggerTest() {
        Lead testLead = new Lead(LastName='Test Name 1', Company='Test Company', Email='test@test.com', Phone='123', LeadSource='Phone');

        Test.startTest();
            insert testLead;
            testLead.LastName = 'Test Name 2';
            update testLead;
            delete testLead;
            undelete testLead;
        Test.stopTest();

        List<CustomLog__c> logs = [
            SELECT Type__c, Message__c 
            FROM CustomLog__c 
            WHERE Message__c LIKE 'LeadTriggerHandler%'
        ];
        Assert.areEqual(numberOfLogs, logs.size());
        Assert.areEqual('INFO', logs[0].Type__c);
    }
}